export interface Product {
  slug: string
  name: string
  brand: string
  rating: number
  reviews: number
  price: string
  image: string
  featured: boolean
  keyIngredient: string
  benefits: string[]
  fullDescription?: string
  activeIngredients?: { name: string; concentration: string; benefit: string }[]
  howToUse?: string[]
  bestFor?: string[]
  proscons?: { pros: string[]; cons: string[] }
  amazonLink?: string
}

export const products: Product[] = [
  {
    slug: "nuface-mini-starter-kit",
    name: "NuFACE MINI Starter Kit",
    brand: "NuFACE",
    rating: 4.4,
    reviews: 3820,
    price: "$220.00",
    image: "https://m.media-amazon.com/images/I/71oe9mGIsgL._SX466_.jpg",
    featured: true,
    keyIngredient: "Microcurrent Technology",
    benefits: ["Improved Facial Contour", "Better Skin Tone", "Reduced Wrinkles"],
    fullDescription:
      "A petite, portable microcurrent facial toning device FDA-cleared to improve facial contour, tone, and the look of fine lines and wrinkles.",
    howToUse: [
      "Use 5 minutes a day, 5 times a week for the first 60 days",
      "Then 2-3 times a week for maintenance",
      "Apply gel primer before use",
    ],
    bestFor: ["Loss of firmness", "Fine lines", "Facial contouring"],
    proscons: {
      pros: ["FDA-Cleared", "Portable", "Easy to Use", "Visible results"],
      cons: ["Requires consistent use", "Gel primer needed", "Premium price"],
    },
    amazonLink: "https://www.amazon.com/NuFACE-MINI-Starter-Kit-Microcurrent/dp/B09YCG7Q8V",
  },
  {
    slug: "solawave-4-in-1-red-light-therapy",
    name: "Solawave 4-in-1 Red Light Therapy Wand",
    brand: "Solawave",
    rating: 4.1,
    reviews: 1540,
    price: "$169.00",
    image: "https://m.media-amazon.com/images/I/51qUSsGlHtL._SX466_.jpg",
    featured: true,
    keyIngredient: "Red Light Therapy",
    benefits: ["Reduces wrinkles", "Depuffs skin", "Fades dark spots"],
    fullDescription:
      "Award-winning skincare tool that combines 4 powerful technologies: Red Light Therapy, Microcurrent, Facial Massage, and Therapeutic Warmth for the ultimate at-home spa facial.",
    howToUse: [
      "Glide the wand across your face in an upward and outward motion",
      "Use daily for best results",
      "Pair with your favorite serum",
    ],
    bestFor: ["Anti-aging", "Puffiness", "Dull skin", "All skin types"],
    proscons: {
      pros: ["Multi-functional", "Compact", "Rechargeable", "Award-winning"],
      cons: ["Battery life varies", "Requires daily use"],
    },
    amazonLink: "https://www.amazon.com/Solawave-4-1-Red-Light-Therapy/dp/B0BZ1488WR",
  },
  {
    slug: "dr-dennis-gross-spectralite-faceware",
    name: "Dr. Dennis Gross SpectraLite FaceWare Pro",
    brand: "Dr. Dennis Gross",
    rating: 4.5,
    reviews: 980,
    price: "$455.00",
    image: "https://m.media-amazon.com/images/I/51o0k2-mhnL._SX466_.jpg",
    featured: true,
    keyIngredient: "LED Light Therapy",
    benefits: ["Stimulates collagen", "Destroys acne bacteria", "Evens skin tone"],
    fullDescription:
      "FDA-cleared LED mask with red and blue lights to smooth wrinkles and fight acne. This hands-free device treats the entire face in just 3 minutes.",
    howToUse: [
      "Place device over face and wear for 3 minutes daily",
      "Red light for anti-aging",
      "Blue light for acne treatment",
    ],
    bestFor: ["Fine lines", "Acne", "Uneven tone", "Preventive care"],
    proscons: {
      pros: ["Hands-free", "Short treatment time", "Dermatologist developed", "FDA-cleared"],
      cons: ["Expensive", "One size fits most", "Bulky to store"],
    },
    amazonLink: "https://www.amazon.com/Dr-Dennis-Gross-SpectraLite-FaceWare/dp/B08NCRHNW9",
  },
  {
    slug: "hxdzfx-facial-light-therapy",
    name: "HXDZFX Facial Light Therapy Mask",
    brand: "HXDZFX",
    rating: 4.2,
    reviews: 560,
    price: "$89.99",
    image: "https://m.media-amazon.com/images/I/61Yhh22SaWL._SX466_.jpg",
    featured: false,
    keyIngredient: "7 Color LED Light",
    benefits: ["Anti-aging", "Acne control", "Skin brightening"],
    fullDescription:
      "7-color LED face mask for various skin concerns including aging, acne, pigmentation, and more. Each color targets different skin issues.",
    howToUse: [
      "Use for 15-20 minutes, 3-4 times a week",
      "Select appropriate color for your concern",
      "Clean face before use",
    ],
    bestFor: ["Multiple skin concerns", "Home spa treatments", "Budget-conscious"],
    proscons: {
      pros: ["Affordable", "Multiple color options", "Effective"],
      cons: ["Heavy on face", "Requires being plugged in", "Long treatment time"],
    },
    amazonLink: "https://www.amazon.com/HXDZFX-FACIAL-LIGHT-THERAPY-HK207/dp/B091YLCY1J",
  },
  {
    slug: "lilyana-naturals-retinol-cream",
    name: "LilyAna Naturals Retinol Cream",
    brand: "LilyAna Naturals",
    rating: 4.6,
    reviews: 25000,
    price: "$22.99",
    image: "https://m.media-amazon.com/images/I/81D1oGK74aL._SX466_.jpg",
    featured: true,
    keyIngredient: "Retinol",
    benefits: ["Fades acne scars", "Hydrates skin", "Evens texture"],
    fullDescription:
      "Advanced anti-aging formula to reduce fine lines, wrinkles, and sun damage. Combines retinol with natural ingredients for gentle yet effective results.",
    activeIngredients: [
      { name: "Retinol", concentration: "2.5%", benefit: "Reduces fine lines and wrinkles" },
      { name: "Hyaluronic Acid", concentration: "N/A", benefit: "Deep hydration" },
      { name: "Vitamin E", concentration: "N/A", benefit: "Antioxidant protection" },
      { name: "Green Tea", concentration: "N/A", benefit: "Soothes skin" },
    ],
    howToUse: [
      "Apply to cleansed face and neck morning and night",
      "Start with every other day if new to retinol",
      "Always use sunscreen during the day",
    ],
    bestFor: ["Fine lines", "Acne scars", "Sun damage", "All skin types"],
    proscons: {
      pros: ["Natural ingredients", "Cruelty-free", "Non-greasy", "Great value", "High rating"],
      cons: ["May cause purging initially", "Takes time to see results"],
    },
    amazonLink: "https://www.amazon.com/LilyAna-Naturals-Retinol-Cream-Moisturizer/dp/B01ES349CY",
  },
  {
    slug: "glo24k-rejuvenation-beauty-device",
    name: "GLO24K Skin Rejuvenation Beauty Device",
    brand: "GLO24K",
    rating: 4.0,
    reviews: 320,
    price: "$89.00",
    image: "https://m.media-amazon.com/images/I/51D1XPOzXgL._AC_SX679_.jpg",
    featured: false,
    keyIngredient: "LED + Vibration",
    benefits: ["Neck lifting", "Skin tightening", "Better product absorption"],
    fullDescription:
      "Advanced skincare tool for face and neck featuring LED light therapy, thermal therapy, and vibration technologies for lifting and tightening effects.",
    howToUse: [
      "Massage on face and neck in upward motions",
      "Use with your favorite serum or cream",
      "5-10 minutes daily",
    ],
    bestFor: ["Neck sagging", "Loss of firmness", "Product absorption"],
    proscons: {
      pros: ["Ergonomic design", "Easy to use", "Multi-functional"],
      cons: ["Takes time to see results", "Needs charging"],
    },
    amazonLink: "https://www.amazon.com/GLO24K-Rejuvenation-Vibration-Technologies-Appearance/dp/B0947W9C43",
  },
  {
    slug: "nuderma-clinical-skin-therapy",
    name: "NuDerma Clinical Skin Therapy Wand",
    brand: "NuDerma",
    rating: 4.4,
    reviews: 4100,
    price: "$79.95",
    image: "https://m.media-amazon.com/images/I/61QJrCO3-QL._AC_SX679_.jpg",
    featured: false,
    keyIngredient: "High Frequency",
    benefits: ["Treats acne", "Reduces wrinkles", "Tightens skin"],
    fullDescription:
      "High frequency machine to boost cell turnover and improve skin profile. Includes 6 different wands for various treatments.",
    howToUse: [
      "Use 2-3 times a week for 10-15 minutes",
      "Select appropriate wand for treatment area",
      "Move in circular motions over skin",
    ],
    bestFor: ["Acne treatment", "Skin tightening", "Hair growth", "Cellulite"],
    proscons: {
      pros: ["Includes 6 wands", "Clinical grade", "Versatile", "Good value"],
      cons: ["Strong smell of ozone", "Can be intimidating to use"],
    },
    amazonLink: "https://www.amazon.com/NuDerma-Clinical-Skin-Therapy-Wand/dp/B086M3XRK1",
  },
  {
    slug: "mlay-rf-skin-tightening-machine",
    name: "MLAY RF Skin Tightening Machine",
    brand: "MLAY",
    rating: 4.3,
    reviews: 1200,
    price: "$299.99",
    image: "https://m.media-amazon.com/images/I/51HXmMw-BhL._SX466_.jpg",
    featured: false,
    keyIngredient: "Radio Frequency",
    benefits: ["Stimulates collagen", "Lifts sagging skin", "Reduces wrinkles"],
    fullDescription:
      "Professional radio frequency device for anti-aging and skin lifting. RF technology heats the deep layers of skin to stimulate collagen production.",
    howToUse: ["Use once a week for 20 minutes", "Apply RF gel before treatment", "Move device in circular motions"],
    bestFor: ["Sagging skin", "Wrinkles", "Body contouring", "Cellulite"],
    proscons: {
      pros: ["Safe and effective", "Long-lasting results", "Professional grade"],
      cons: ["Gel required", "Time consuming", "Expensive"],
    },
    amazonLink: "https://www.amazon.com/MLAY-RF-Skin-Tightening-Machine/dp/B01IBSX35Q",
  },
  {
    slug: "loreal-collagen-moisture-filler",
    name: "L'Oreal Paris Collagen Moisture Filler",
    brand: "L'Oreal Paris",
    rating: 4.5,
    reviews: 45000,
    price: "$11.49",
    image: "https://m.media-amazon.com/images/I/71ZsyfE7q+L._SX466_.jpg",
    featured: false,
    keyIngredient: "Collagen",
    benefits: ["Intense hydration", "Plumps skin", "Fills wrinkles"],
    fullDescription:
      "Day and night cream that restores cushion to skin and smooths wrinkles. Infused with collagen to replump and hydrate mature skin.",
    howToUse: [
      "Apply every morning and evening to face",
      "Massage gently until absorbed",
      "Can be used on neck and décolleté",
    ],
    bestFor: ["Dry skin", "Wrinkles", "Mature skin", "Daily moisturizing"],
    proscons: {
      pros: ["Affordable", "Lightweight", "Effective hydration", "Drugstore brand"],
      cons: ["Fragrance may irritate some", "Not heavy-duty anti-aging"],
    },
    amazonLink: "https://www.amazon.com/Face-Moisturizer-Collagen-Cream-Moisturizing/dp/B0BBSP2JNQ",
  },
  {
    slug: "tree-hut-shea-sugar-scrub",
    name: "Tree Hut Shea Sugar Scrub Variety Pack",
    brand: "Tree Hut",
    rating: 4.7,
    reviews: 35000,
    price: "$10.99",
    image: "https://m.media-amazon.com/images/I/5185Sq0awQL._SX466_.jpg",
    featured: false,
    keyIngredient: "Shea Butter + Sugar",
    benefits: ["Exfoliates", "Hydrates", "Softens skin"],
    fullDescription:
      "Exfoliating body scrub that removes dull skin to reveal glowing skin. Made with real sugar, shea butter, and natural oils for smooth, soft skin.",
    howToUse: [
      "Massage onto wet skin in circular motions",
      "Focus on rough areas like elbows and knees",
      "Rinse thoroughly",
      "Use 2-3 times a week",
    ],
    bestFor: ["Body exfoliation", "Dry skin", "Rough patches", "Self-care routine"],
    proscons: {
      pros: ["Great scent", "Effective exfoliation", "Affordable", "Moisturizing"],
      cons: ["Can be abrasive on sensitive skin", "Messy in shower"],
    },
    amazonLink: "https://www.amazon.com/Tree-Hut-Variety-Strawberry-Champaine/dp/B0BX2TZZWG",
  },
  {
    slug: "cerave-skin-renewing-night-cream",
    name: "CeraVe Skin Renewing Night Cream",
    brand: "CeraVe",
    rating: 4.6,
    reviews: 28000,
    price: "$19.99",
    image: "https://m.media-amazon.com/images/I/516r6ghtxaL._SL1000_.jpg",
    featured: true,
    keyIngredient: "Peptides + Ceramides",
    benefits: ["Restores skin barrier", "Softens skin", "Hydrates overnight"],
    fullDescription:
      "Night cream with peptides and ceramides to refresh tired skin. Features MVE technology for all-night hydration and niacinamide to help calm skin.",
    activeIngredients: [
      { name: "Peptides", concentration: "N/A", benefit: "Support skin renewal" },
      { name: "Ceramides", concentration: "N/A", benefit: "Restore protective barrier" },
      { name: "Hyaluronic Acid", concentration: "N/A", benefit: "Retains moisture" },
      { name: "Niacinamide", concentration: "N/A", benefit: "Calms skin" },
    ],
    howToUse: [
      "Apply in small dots around face and smooth gently",
      "Use at night after cleansing",
      "Can be used on face and neck",
    ],
    bestFor: ["All skin types", "Dry skin", "Sensitive skin", "Barrier repair"],
    proscons: {
      pros: ["Fragrance-free", "Non-comedogenic", "Dermatologist recommended", "Great value"],
      cons: ["Thick texture", "Small bottle for price"],
    },
    amazonLink: "https://www.amazon.com/CeraVe-Hyaluronic-Ceramides-Niacinamide-Non-Drying/dp/B01N1LL62W",
  },
  {
    slug: "mighty-patch-original",
    name: "Mighty Patch Original",
    brand: "Hero Cosmetics",
    rating: 4.8,
    reviews: 85000,
    price: "$12.99",
    image: "https://m.media-amazon.com/images/I/51Kx4Wt+VqL._SL1500_.jpg",
    featured: true,
    keyIngredient: "Hydrocolloid",
    benefits: ["Absorbs impurities", "Protects pimple", "Faster healing"],
    fullDescription:
      "Hydrocolloid acne pimple patch for covering zits and blemishes. Works overnight to absorb pimple gunk and protect from picking.",
    howToUse: [
      "Apply to clean, dry skin over the pimple",
      "Leave on for 6-8 hours or overnight",
      "Remove and dispose",
      "Use as needed",
    ],
    bestFor: ["Active pimples", "Whitehead extraction", "Preventing picking"],
    proscons: {
      pros: ["Works overnight", "Invisible on skin", "Drugstore available", "Effective"],
      cons: ["Pricey per patch", "Only works on surface pimples"],
    },
    amazonLink: "https://www.amazon.com/Mighty-Patch-Hydrocolloid-Absorbing-count/dp/B074PVTPBW",
  },
  {
    slug: "medicube-zero-pore-pads",
    name: "Medicube Zero Pore Pads",
    brand: "Medicube",
    rating: 4.4,
    reviews: 2300,
    price: "$28.00",
    image: "https://m.media-amazon.com/images/I/71Mcspt-6AL._AC_SX679_.jpg",
    featured: false,
    keyIngredient: "AHA/BHA",
    benefits: ["Tightens pores", "Exfoliates", "Controls oil"],
    fullDescription:
      "Dual-textured toner pads to tighten pores and control sebum. Features Anti-Sebum P complex and chemical exfoliants for clearer skin.",
    activeIngredients: [
      { name: "AHA", concentration: "N/A", benefit: "Exfoliates surface" },
      { name: "BHA", concentration: "N/A", benefit: "Cleans pores" },
      { name: "Anti-Sebum P", concentration: "N/A", benefit: "Controls oil" },
    ],
    howToUse: [
      "Swipe across face after cleansing",
      "Use textured side first, then smooth side",
      "No need to rinse",
      "Use daily or as needed",
    ],
    bestFor: ["Large pores", "Oily skin", "Blackheads", "Texture"],
    proscons: {
      pros: ["Convenient pads", "Effective pore care", "Dual texture", "K-beauty"],
      cons: ["Can be sticky", "Expensive per pad"],
    },
    amazonLink: "https://www.amazon.com/Medicube-Zero-Pore-Pads-Dual-Textured/dp/B09V7Z4TJG",
  },
  {
    slug: "cosrx-advanced-snail-96-mucin",
    name: "COSRX Advanced Snail 96 Mucin Power Essence",
    brand: "COSRX",
    rating: 4.6,
    reviews: 42000,
    price: "$25.00",
    image: "https://m.media-amazon.com/images/I/416kUGx2rQL._SL1024_.jpg",
    featured: true,
    keyIngredient: "Snail Mucin 96%",
    benefits: ["Hydrates", "Repairs skin", "Soothes irritation"],
    fullDescription:
      "Lightweight essence capable of repairing damaged skin and improving elasticity. Contains 96.3% snail secretion filtrate for maximum hydration and repair.",
    activeIngredients: [
      { name: "Snail Secretion Filtrate", concentration: "96.3%", benefit: "Repairs and hydrates" },
      { name: "Sodium Hyaluronate", concentration: "N/A", benefit: "Additional moisture" },
    ],
    howToUse: [
      "Apply small amount on face after cleansing and toning",
      "Pat gently until absorbed",
      "Use morning and evening",
      "Layer with other products",
    ],
    bestFor: ["Dehydrated skin", "Damaged barrier", "Sensitive skin", "All skin types"],
    proscons: {
      pros: ["Highly hydrating", "No fragrance", "Gentle", "K-beauty favorite", "Great reviews"],
      cons: ["Sticky texture", "Slow to absorb"],
    },
    amazonLink: "https://www.amazon.com/COSRX-Repairing-Hydrating-Secretion-Phthalates/dp/B00PBX3L7K",
  },
  {
    slug: "biodance-bio-collagen-mask",
    name: "Biodance Bio-Collagen Real Deep Mask",
    brand: "Biodance",
    rating: 4.3,
    reviews: 1500,
    price: "$19.00",
    image: "https://m.media-amazon.com/images/I/51Qiwz3ZiaL._SX466_.jpg",
    featured: false,
    keyIngredient: "Low Molecular Collagen",
    benefits: ["Pore tightening", "Deep hydration", "Elasticity boost"],
    fullDescription:
      "Overnight mask that becomes transparent as ingredients absorb into skin. Features low molecular weight collagen for deep penetration and visible results.",
    howToUse: [
      "Apply mask after cleansing",
      "Leave on for 3-4 hours or overnight",
      "Remove and pat in remaining essence",
      "Use 2-3 times a week",
    ],
    bestFor: ["Dehydrated skin", "Large pores", "Loss of elasticity", "Special occasions"],
    proscons: {
      pros: ["Innovative texture", "Visible results", "Long-wear", "Hydrating"],
      cons: ["Requires long wear time", "Can slip off", "Pricey per mask"],
    },
    amazonLink: "https://www.amazon.com/Biodance-Bio-Collagen-Tightening-Hydrating-Molecular/dp/B0B2RM68G2",
  },
  {
    slug: "the-ordinary-hyaluronic-acid",
    name: "The Ordinary Hyaluronic Acid 2% + B5",
    brand: "The Ordinary",
    rating: 4.6,
    reviews: 38000,
    price: "$8.90",
    image: "https://m.media-amazon.com/images/I/61eH32lVpdL._SX522_.jpg",
    featured: true,
    keyIngredient: "Hyaluronic Acid 2%",
    benefits: ["Deep hydration", "Plumps skin", "Smoother texture"],
    fullDescription:
      "Hydrating formula with ultra-pure, vegan hyaluronic acid. Multiple molecular weights penetrate different skin layers for comprehensive hydration.",
    activeIngredients: [
      { name: "Hyaluronic Acid", concentration: "2%", benefit: "Multi-depth hydration" },
      { name: "Vitamin B5", concentration: "N/A", benefit: "Enhances hydration" },
    ],
    howToUse: [
      "Apply a few drops to face AM and PM before creams",
      "Apply to damp skin for best results",
      "Can be layered with other serums",
    ],
    bestFor: ["All skin types", "Dehydration", "Plumping", "Budget-friendly"],
    proscons: {
      pros: ["Very affordable", "Effective", "Clean formula", "Cult favorite"],
      cons: ["Can pill if layered incorrectly", "Basic formula"],
    },
    amazonLink: "https://www.amazon.com/Ordinary-Hyaluronic-Acid-2-30ml/dp/B01MYEZPC8",
  },
  {
    slug: "cerave-pm-facial-moisturizing-lotion",
    name: "CeraVe PM Facial Moisturizing Lotion",
    brand: "CeraVe",
    rating: 4.7,
    reviews: 52000,
    price: "$15.99",
    image: "https://m.media-amazon.com/images/I/71jdcrAdwbL._SL1500_.jpg",
    featured: false,
    keyIngredient: "Niacinamide",
    benefits: ["Restores barrier", "Calms skin", "Oil-free hydration"],
    fullDescription:
      "Ultra-lightweight night moisturizer with ceramides and niacinamide. Oil-free formula helps restore the protective skin barrier while calming the skin.",
    activeIngredients: [
      { name: "Ceramides", concentration: "N/A", benefit: "Restore barrier" },
      { name: "Niacinamide", concentration: "N/A", benefit: "Calm and brighten" },
      { name: "Hyaluronic Acid", concentration: "N/A", benefit: "Hydrate" },
    ],
    howToUse: ["Apply liberally to face and neck at night", "Use after serums", "Suitable for daily use"],
    bestFor: ["All skin types", "Oily skin", "Sensitive skin", "Nighttime routine"],
    proscons: {
      pros: ["Lightweight", "Oil-free", "Dermatologist developed", "Affordable"],
      cons: ["Small bottle", "Not moisturizing enough for very dry skin"],
    },
    amazonLink: "https://www.amazon.com/CeraVe-Facial-Moisturizing-Lotion-Lightweight/dp/B00365DABC",
  },
  {
    slug: "drmtlgy-anti-aging-tinted-moisturizer",
    name: "DRMTLGY Anti-Aging Tinted Moisturizer SPF 46",
    brand: "DRMTLGY",
    rating: 4.5,
    reviews: 4800,
    price: "$28.00",
    image: "https://m.media-amazon.com/images/I/31XJef0MOQL._SY300_SX300_QL70_FMwebp_.jpg",
    featured: false,
    keyIngredient: "Zinc Oxide SPF 46",
    benefits: ["Sun protection", "Light coverage", "Anti-aging"],
    fullDescription:
      "Universal tint moisturizer with SPF 46 for all skin types. Provides sun protection, light coverage, and anti-aging benefits in one step.",
    activeIngredients: [
      { name: "Zinc Oxide", concentration: "SPF 46", benefit: "Broad spectrum protection" },
      { name: "Niacinamide", concentration: "N/A", benefit: "Brightens and calms" },
      { name: "Hyaluronic Acid", concentration: "N/A", benefit: "Hydrates" },
    ],
    howToUse: [
      "Apply liberally 15 minutes before sun exposure",
      "Reapply every 2 hours",
      "Can be used as primer under makeup",
    ],
    bestFor: ["Daily sun protection", "Light coverage", "All skin types", "No white cast"],
    proscons: {
      pros: ["No white cast", "Glowy finish", "High SPF", "Multi-tasking"],
      cons: ["Shiny on oily skin", "Limited shade range"],
    },
    amazonLink: "https://www.amazon.com/DRMTLGY-Anti-Aging-Moisturizer-Foundation-Protection/dp/B07RW4CHC3",
  },
  {
    slug: "daolyo-hydrocolloid-patches",
    name: "Daolyo Hydrocolloid Blemish Patches",
    brand: "Daolyo",
    rating: 4.4,
    reviews: 850,
    price: "$9.99",
    image: "https://m.media-amazon.com/images/I/61DIM4JOLiL._SL1500_.jpg",
    featured: false,
    keyIngredient: "Hydrocolloid + Salicylic Acid",
    benefits: ["Reduces redness", "Absorbs pus", "Calms inflammation"],
    fullDescription:
      "Pimple patches with salicylic acid and calendula for faster healing. Variety of sizes to fit different blemishes.",
    howToUse: ["Apply to clean skin and leave overnight", "Remove in the morning", "Replace if needed"],
    bestFor: ["Active breakouts", "Reducing inflammation", "Overnight treatment"],
    proscons: {
      pros: ["Variety of sizes", "Added ingredients", "Affordable", "Effective"],
      cons: ["Adhesion varies", "Thicker than some brands"],
    },
    amazonLink: "https://www.amazon.com/Daolyo-Hydrocolloid-Blemishes-Salicylic-Calendula/dp/B0CCRWC6W9",
  },
  {
    slug: "loreal-paris-collagen-moisturizer",
    name: "L'Oreal Paris Collagen Day/Night Cream",
    brand: "L'Oreal Paris",
    rating: 4.5,
    reviews: 46000,
    price: "$11.49",
    image: "https://m.media-amazon.com/images/I/71jTuSY+xSL._SX466_.jpg",
    featured: false,
    keyIngredient: "Collagen",
    benefits: ["Smooths wrinkles", "Plumps skin", "Hydrates"],
    fullDescription:
      "Intense hydration face cream to fill in wrinkles and fine lines. Formulated with collagen to restore skin's cushiony feel.",
    howToUse: ["Apply to face and neck morning and night", "Massage gently in upward motions", "Use after serum"],
    bestFor: ["Mature skin", "Dry skin", "Wrinkles", "Budget-friendly"],
    proscons: {
      pros: ["Inexpensive", "Proven results", "Drugstore accessible", "Rich texture"],
      cons: ["Basic formula", "Fragrance present"],
    },
    amazonLink: "https://www.amazon.com/LOr%C3%A9al-Collagen-Moisturizer-Reduce-Wrinkles/dp/B002JDUMFO",
  },
  {
    slug: "vt-cosmetics-cica-mask",
    name: "VT COSMETICS CICA Daily Soothing Mask",
    brand: "VT COSMETICS",
    rating: 4.5,
    reviews: 1800,
    price: "$24.00",
    image: "https://m.media-amazon.com/images/I/614+ZmQNCML._SX466_.jpg",
    featured: false,
    keyIngredient: "Centella Asiatica (Cica)",
    benefits: ["Soothes irritation", "Hydrates", "Reduces redness"],
    fullDescription:
      "Quick soothing mask sheet for tired and dry skin. Infused with cica to calm irritation and hyaluronic acid for hydration.",
    activeIngredients: [
      { name: "Centella Asiatica", concentration: "N/A", benefit: "Soothes and repairs" },
      { name: "Hyaluronic Acid", concentration: "N/A", benefit: "Deep hydration" },
    ],
    howToUse: ["Apply for 10-15 minutes daily", "Remove and pat in remaining essence", "No need to rinse"],
    bestFor: ["Sensitive skin", "Irritated skin", "Redness", "Quick hydration"],
    proscons: {
      pros: ["Convenient packaging", "Gentle", "Effective", "Good value pack"],
      cons: ["Thin sheets", "Basic formula"],
    },
    amazonLink: "https://www.amazon.com/VT-COSMETICS-Daily-Soothing-Mask/dp/B083X5R6VR",
  },
  {
    slug: "tonymoly-tako-pore-blackhead-scrub",
    name: "TONYMOLY Tako Pore Blackhead Scrub Stick",
    brand: "TONYMOLY",
    rating: 4.1,
    reviews: 2500,
    price: "$12.50",
    image: "https://m.media-amazon.com/images/I/51s9IzYEVfL._SL1500_.jpg",
    featured: false,
    keyIngredient: "Charcoal",
    benefits: ["Removes blackheads", "Exfoliates", "Clears pores"],
    fullDescription:
      "Stick scrub that extracts blackheads and whiteheads. Features charcoal and mud to deep clean pores on the nose and T-zone.",
    howToUse: [
      "Wet nose and scrub stick",
      "Massage onto damp nose in circular motions",
      "Rinse off thoroughly",
      "Use 1-2 times per week",
    ],
    bestFor: ["Blackheads", "Clogged pores", "Oily nose", "T-zone"],
    proscons: {
      pros: ["Cute packaging", "Easy to target areas", "Travel-friendly", "K-beauty"],
      cons: ["Can be drying", "Messy", "Not for whole face"],
    },
    amazonLink: "https://www.amazon.com/TONYMOLY-Tako-Blackhead-Scrub-Stick/dp/B075GWQMP6",
  },
  {
    slug: "24k-gold-under-eye-patches",
    name: "24K Gold Under Eye Patches",
    brand: "Generic",
    rating: 4.3,
    reviews: 12000,
    price: "$19.99",
    image: "https://m.media-amazon.com/images/I/71klB9KjwIL._SL1500_.jpg",
    featured: false,
    keyIngredient: "24K Gold",
    benefits: ["Depuffs", "Brightens", "Hydrates"],
    fullDescription:
      "Anti-aging eye masks to reduce dark circles and puffiness. Infused with 24K nano gold, collagen, and hyaluronic acid for luxurious under-eye care.",
    activeIngredients: [
      { name: "24K Nano Gold", concentration: "N/A", benefit: "Anti-aging and brightening" },
      { name: "Collagen", concentration: "N/A", benefit: "Firms and plumps" },
      { name: "Hyaluronic Acid", concentration: "N/A", benefit: "Hydrates" },
    ],
    howToUse: ["Place under eyes for 20 minutes", "Use 2-3 times per week", "Store in fridge for extra cooling effect"],
    bestFor: ["Dark circles", "Puffiness", "Tired eyes", "Self-care"],
    proscons: {
      pros: ["Cooling effect", "Large quantity", "Affordable", "Luxurious feel"],
      cons: ["Slippery", "Can slide down", "One-time use"],
    },
    amazonLink: "https://www.amazon.com/Under-Eye-Patches-Gold-24-Pairs/dp/B014E2D6BY",
  },
  {
    slug: "good-molecules-retinol-cream",
    name: "Good Molecules Gentle Retinol Cream",
    brand: "Good Molecules",
    rating: 4.6,
    reviews: 1100,
    price: "$8.00",
    image: "https://m.media-amazon.com/images/I/71kaC5NIrBL._SX466_.jpg",
    featured: false,
    keyIngredient: "Retinol 0.1%",
    benefits: ["Anti-aging", "Smooths texture", "Gentle formula"],
    fullDescription:
      "Gentle retinol treatment for beginners to soften fine lines. Combines 0.1% retinol with bakuchiol and grapeseed oil for a gentle yet effective formula.",
    activeIngredients: [
      { name: "Retinol", concentration: "0.1%", benefit: "Anti-aging" },
      { name: "Bakuchiol", concentration: "N/A", benefit: "Boosts retinol, reduces irritation" },
      { name: "Grapeseed Oil", concentration: "N/A", benefit: "Antioxidant and moisturizing" },
    ],
    howToUse: [
      "Apply pea-sized amount at night",
      "Start 2-3 times per week",
      "Gradually increase frequency",
      "Always use sunscreen during the day",
    ],
    bestFor: ["Retinol beginners", "Sensitive skin", "Fine lines", "Budget-friendly"],
    proscons: {
      pros: ["Gentle", "Affordable", "Clean formula", "Good for beginners"],
      cons: ["Low concentration for advanced users", "Takes longer to see results"],
    },
    amazonLink: "https://www.amazon.com/Good-Molecules-Formulated-Revitalize-Fragrance/dp/B091NJQ29P",
  },
  {
    slug: "the-ordinary-caffeine-solution",
    name: "The Ordinary Caffeine Solution 5% + EGCG",
    brand: "The Ordinary",
    rating: 4.4,
    reviews: 32000,
    price: "$7.50",
    image: "https://m.media-amazon.com/images/I/51uLZFalWFL._SL1240_.jpg",
    featured: false,
    keyIngredient: "Caffeine 5%",
    benefits: ["Reduces puffiness", "Brightens dark circles", "De-puffs"],
    fullDescription:
      "Light-textured formula to reduce eye contour pigmentation and puffiness. Contains high concentration of caffeine and EGCG from green tea.",
    activeIngredients: [
      { name: "Caffeine", concentration: "5%", benefit: "Reduces puffiness" },
      { name: "EGCG", concentration: "N/A", benefit: "Green tea antioxidant" },
    ],
    howToUse: [
      "Massage small amount onto eye contour AM and PM",
      "Pat gently, don't rub",
      "Use before heavier eye creams",
    ],
    bestFor: ["Puffy eyes", "Dark circles", "Tired eyes", "Budget-friendly"],
    proscons: {
      pros: ["Very affordable", "Lasts long", "Effective de-puffing", "Simple formula"],
      cons: ["Can be drying", "Thin consistency", "No applicator"],
    },
    amazonLink: "https://www.amazon.com/Ordinary-Caffeine-Solution-EGCG-30ml/dp/B01MUZVE1C",
  },
  {
    slug: "drmtlgy-luminous-eye-corrector",
    name: "DRMTLGY Luminous Eye Corrector SPF 41",
    brand: "DRMTLGY",
    rating: 4.3,
    reviews: 850,
    price: "$44.00",
    image: "https://m.media-amazon.com/images/I/61f+2yILldL._SX466_.jpg",
    featured: false,
    keyIngredient: "SPF 41 + Peptides",
    benefits: ["Conceals dark circles", "Sun protection", "Anti-aging"],
    fullDescription:
      "Brightening eye treatment with SPF 41 to protect and correct. Multitasking product that conceals, treats, and protects the delicate under-eye area.",
    activeIngredients: [
      { name: "Peptides", concentration: "N/A", benefit: "Anti-aging" },
      { name: "Ceramides", concentration: "N/A", benefit: "Barrier support" },
      { name: "SPF 41", concentration: "Broad Spectrum", benefit: "Sun protection" },
    ],
    howToUse: [
      "Apply to under-eye area and blend",
      "Use as concealer or alone",
      "Reapply throughout day for sun protection",
    ],
    bestFor: ["Dark circles", "Sun protection", "Multitasking", "On-the-go"],
    proscons: {
      pros: ["Multitasking product", "Metal applicator", "SPF protection", "Peptides"],
      cons: ["Limited shade range", "Expensive", "Can crease"],
    },
    amazonLink: "https://www.amazon.com/DRMTLGY-Corrector-Anti-Aging-Hydrating-Undertone/dp/B0CRXHWR48",
  },
  {
    slug: "grace-and-stella-caffeine-eye-serum",
    name: "grace & stella Caffeine Eye Serum",
    brand: "grace & stella",
    rating: 4.2,
    reviews: 450,
    price: "$19.95",
    image: "https://m.media-amazon.com/images/I/71aa2KWHjxL._SX466_.jpg",
    featured: false,
    keyIngredient: "Caffeine",
    benefits: ["Depuffs", "Hydrates", "Brightens"],
    fullDescription:
      "Energizing serum to wake up tired eyes and reduce bags. Features cooling rollerball applicator for easy, mess-free application.",
    activeIngredients: [
      { name: "Caffeine", concentration: "N/A", benefit: "Reduces puffiness" },
      { name: "Peptides", concentration: "N/A", benefit: "Anti-aging" },
      { name: "Green Tea", concentration: "N/A", benefit: "Antioxidant protection" },
    ],
    howToUse: [
      "Roll onto under-eye area morning and night",
      "Gently pat to absorb",
      "Store in fridge for extra cooling",
    ],
    bestFor: ["Morning puffiness", "Tired eyes", "Dark circles", "Quick application"],
    proscons: {
      pros: ["Cooling rollerball", "Vegan", "Easy to use", "Mess-free"],
      cons: ["Roller can stick", "Small size", "Basic formula"],
    },
    amazonLink: "https://www.amazon.com/grace-stella-Caffeine-Serum-Puffing/dp/B0D9PMVR92",
  },
  {
    slug: "bio-oil-skincare-oil",
    name: "Bio-Oil Skincare Oil",
    brand: "Bio-Oil",
    rating: 4.7,
    reviews: 95000,
    price: "$26.50",
    image: "https://m.media-amazon.com/images/I/61rtO5x7T-L._SX466_.jpg",
    featured: true,
    keyIngredient: "Vitamin A & E",
    benefits: ["Improves scars", "Hydrates", "Evens tone"],
    fullDescription:
      "Specialist skincare oil for scars, stretch marks, and uneven skin tone. Lightweight formula absorbs quickly and improves the appearance of various skin concerns.",
    activeIngredients: [
      { name: "Vitamin A", concentration: "N/A", benefit: "Skin renewal" },
      { name: "Vitamin E", concentration: "N/A", benefit: "Antioxidant" },
      { name: "Chamomile Oil", concentration: "N/A", benefit: "Calming" },
    ],
    howToUse: [
      "Massage into affected areas twice daily",
      "Use for minimum 3 months for scars",
      "Can be used on face and body",
    ],
    bestFor: ["Scars", "Stretch marks", "Uneven tone", "Dry patches"],
    proscons: {
      pros: ["Effective for marks", "Absorbs well", "Multi-purpose", "Cult favorite", "High reviews"],
      cons: ["Oily texture", "Fragrance present", "Takes time"],
    },
    amazonLink: "https://www.amazon.com/Bio-Oil-Skincare-Vitamin-Stretchmarks-Moisturizer/dp/B000VPPUEA",
  },
  {
    slug: "maree-gold-collagen-eye-gels",
    name: "MAREE Gold Collagen Eye Gels",
    brand: "MAREE",
    rating: 4.4,
    reviews: 3200,
    price: "$24.95",
    image: "https://m.media-amazon.com/images/I/814IQCZbskL._SL1500_.jpg",
    featured: false,
    keyIngredient: "Marine Collagen",
    benefits: ["Hydrates", "Brightens", "Soothes"],
    fullDescription:
      "Sparkling eye masks to hydrate and rejuvenate the under-eye area. Infused with marine collagen, hyaluronic acid, and pearl extract for luxurious eye care.",
    activeIngredients: [
      { name: "Marine Collagen", concentration: "N/A", benefit: "Firms and plumps" },
      { name: "Hyaluronic Acid", concentration: "N/A", benefit: "Deep hydration" },
      { name: "Pearl Extract", concentration: "N/A", benefit: "Brightens" },
    ],
    howToUse: ["Apply for 15-20 minutes", "Use 2-3 times per week", "Can be used on other areas like forehead"],
    bestFor: ["Dry under-eyes", "Fine lines", "Dark circles", "Self-care ritual"],
    proscons: {
      pros: ["Beautiful packaging", "Lots of serum", "Effective", "Good value"],
      cons: ["Can slide down", "One-time use", "Storage required"],
    },
    amazonLink: "https://www.amazon.com/MAREE-Gold-Collagen-Facial-Hyaluronic/dp/B0CNDCKXDX",
  },
  {
    slug: "roselynboutique-microdermabrasion-kit",
    name: "RoselynBoutique Microdermabrasion Kit",
    brand: "RoselynBoutique",
    rating: 4.1,
    reviews: 1800,
    price: "$39.99",
    image: "https://m.media-amazon.com/images/I/61g4JnvW2FL._SL1500_.jpg",
    featured: false,
    keyIngredient: "Diamond Microdermabrasion",
    benefits: ["Exfoliates dead skin", "Clears pores", "Smooths texture"],
    fullDescription:
      "At-home facial tool to exfoliate and suction away impurities. Features diamond tip for physical exfoliation and vacuum suction to clear pores.",
    howToUse: [
      "Glide over face once a week",
      "Use on clean, dry skin",
      "Start with lowest suction setting",
      "Clean heads after each use",
    ],
    bestFor: ["Dull skin", "Blackheads", "Rough texture", "Home treatments"],
    proscons: {
      pros: ["Deep clean", "Adjustable suction", "Multiple heads", "At-home spa"],
      cons: ["Can cause bruising if used incorrectly", "Loud", "Learning curve"],
    },
    amazonLink: "https://www.amazon.com/ROSELYNBOUTIQUE-Microdermabrasion-Cosmetic-Instrument-Self-Care/dp/B0846PMST3",
  },
  {
    slug: "lymphatic-drainage-massager",
    name: "Lymphatic Drainage Gua Sha Massager",
    brand: "Generic",
    rating: 4.3,
    reviews: 650,
    price: "$18.99",
    image: "https://m.media-amazon.com/images/I/617TGY1GElL._AC_SL1500_.jpg",
    featured: false,
    keyIngredient: "Ergonomic Design",
    benefits: ["Contours jawline", "Depuffs", "Relieves tension"],
    fullDescription:
      "Ergonomic tool to contour face and reduce puffiness through lymphatic drainage massage. Designed to fit facial contours precisely for effective massage.",
    howToUse: [
      "Massage face with oil or serum",
      "Use upward and outward strokes",
      "Focus on jawline, cheeks, and forehead",
      "Use morning or evening",
    ],
    bestFor: ["Facial sculpting", "Puffiness", "TMJ tension", "Natural face lift"],
    proscons: {
      pros: ["Battery-free", "Portable", "Affordable", "Easy to use"],
      cons: ["Manual effort required", "Results temporary", "Needs oil/serum"],
    },
    amazonLink: "https://www.amazon.com/Lymphatic-Drainage-Massager-Ergonomically-Precisely/dp/B0FB2VF3BW",
  },
  {
    slug: "solawave-pimple-patches",
    name: "Solawave Advanced Blemish Patches",
    brand: "Solawave",
    rating: 4.2,
    reviews: 450,
    price: "$18.00",
    image: "https://m.media-amazon.com/images/I/51i7bwSNjOL._SX466_.jpg",
    featured: false,
    keyIngredient: "Hydrocolloid + Salicylic Acid",
    benefits: ["Spot treatment", "Speeds recovery", "Prevents picking"],
    fullDescription:
      "Innovative patches to target blemishes and promote healing. Premium hydrocolloid patches with added ingredients for faster results.",
    howToUse: [
      "Apply to blemish and leave on",
      "Can be worn overnight or during day",
      "Replace when patch turns white",
    ],
    bestFor: ["Active breakouts", "Cystic acne", "Spot treatment", "Quick healing"],
    proscons: {
      pros: ["Effective", "Brand quality", "Discreet", "Added actives"],
      cons: ["Fewer patches per pack", "Expensive", "Premium pricing"],
    },
    amazonLink: "https://www.amazon.com/Solawave-Treatment-Therapy-Patches-Products/dp/B0B3F4RVHL",
  },
  {
    slug: "elishine-face-massager",
    name: "ELISHINE Vibrating Face Massager",
    brand: "ELISHINE",
    rating: 4.0,
    reviews: 280,
    price: "$22.99",
    image: "https://m.media-amazon.com/images/I/61GZ12tMm+L._SX466_.jpg",
    featured: false,
    keyIngredient: "Vibration Therapy",
    benefits: ["Relaxes muscles", "Improves circulation", "Firms skin"],
    fullDescription:
      "Vibrating facial device to firm and smooth skin. Multiple vibration modes help products absorb better while providing relaxing massage.",
    howToUse: ["Use daily with skincare products", "Glide over face in upward motions", "5-10 minutes per session"],
    bestFor: ["Product absorption", "Relaxation", "Circulation", "At-home spa"],
    proscons: {
      pros: ["Simple to use", "Inexpensive", "Rechargeable", "Good for beginners"],
      cons: ["Basic functionality", "Weak vibration", "Build quality"],
    },
    amazonLink: "https://www.amazon.com/ELISHINE-Massager-Therapy-Firming-Smoothing/dp/B0FB3QVGHQ",
  },
  {
    slug: "beard-club-derma-roller",
    name: "Beard Club Derma Roller 0.5mm",
    brand: "Beard Club",
    rating: 4.4,
    reviews: 5600,
    price: "$19.00",
    image: "https://m.media-amazon.com/images/I/71S2+aqrRgL._SX466_.jpg",
    featured: false,
    keyIngredient: "540 Titanium Microneedles",
    benefits: ["Stimulates follicles", "Increases absorption", "Improves texture"],
    fullDescription:
      "Microneedling tool to stimulate hair growth and improve skin texture. Features 540 titanium needles for effective collagen induction therapy.",
    howToUse: [
      "Roll over clean skin 1-2 times a week",
      "Apply gentle pressure",
      "Follow with serum",
      "Sanitize before and after each use",
    ],
    bestFor: ["Hair growth", "Beard growth", "Product absorption", "Scarring"],
    proscons: {
      pros: ["Effective for growth", "Quality needles", "Affordable", "Multi-purpose"],
      cons: ["Needs careful sanitization", "Can be painful", "Learning curve"],
    },
    amazonLink: "https://www.amazon.com/Beard-Club-Derma-Roller-Scalp/dp/B0DCF8C23S",
  },
  {
    slug: "coslus-facial-cleansing-brush",
    name: "COSLUS Waterproof Facial Cleansing Brush",
    brand: "COSLUS",
    rating: 4.6,
    reviews: 3400,
    price: "$29.99",
    image: "https://m.media-amazon.com/images/I/717o3dLqsVL._AC_SL1500_.jpg",
    featured: false,
    keyIngredient: "Sonic Vibration",
    benefits: ["Deep clean", "Exfoliates", "Removes makeup"],
    fullDescription:
      "Waterproof sonic face scrubber for deep cleansing. Multiple brush heads and speeds for customized cleansing experience.",
    howToUse: [
      "Use with cleanser for 1 minute",
      "Apply gentle pressure",
      "Rinse face and brush after use",
      "Charge when needed",
    ],
    bestFor: ["Deep cleansing", "Makeup removal", "Exfoliation", "Daily use"],
    proscons: {
      pros: ["Waterproof", "Multiple heads", "Good value", "Effective"],
      cons: ["Charging cable specific", "Replacement heads needed", "Can be harsh"],
    },
    amazonLink: "https://www.amazon.com/COSLUS-Facial-Cleansing-Brush-Scrubber/dp/B0CSYW1GR9",
  },
  {
    slug: "gold-bond-ultimate-healing",
    name: "Gold Bond Ultimate Intensive Healing Hand & Body Lotion",
    brand: "Gold Bond",
    rating: 4.8,
    reviews: 42000,
    price: "$14.97",
    image: "https://m.media-amazon.com/images/I/617MgMqO42L._AC_SL1500_.jpg",
    featured: false,
    keyIngredient: "7 Moisturizers + 3 Vitamins",
    benefits: ["Heals dry skin", "Moisturizes", "Non-greasy"],
    fullDescription:
      "Thick, creamy lotion to heal extra dry skin. Formulated with aloe and vitamins for deep moisturization without greasy feel.",
    activeIngredients: [
      { name: "Aloe", concentration: "N/A", benefit: "Soothes and heals" },
      { name: "Vitamins B, C, E", concentration: "N/A", benefit: "Nourish skin" },
    ],
    howToUse: ["Apply daily as needed", "Focus on dry areas like hands, elbows, feet", "Reapply throughout day"],
    bestFor: ["Very dry skin", "Cracked hands", "Winter dryness", "Body care"],
    proscons: {
      pros: ["Very effective", "Good value", "Large size", "Absorbs well", "High reviews"],
      cons: ["Medicinal scent", "Thick texture", "Basic packaging"],
    },
    amazonLink: "https://www.amazon.com/Gold-Bond-Ultimate-Intensive-Healing/dp/B00A8S6HM4",
  },
  {
    slug: "modelones-gel-polish-set",
    name: "Modelones Gel Nail Polish Set",
    brand: "Modelones",
    rating: 4.5,
    reviews: 15000,
    price: "$16.99",
    image: "https://m.media-amazon.com/images/I/81JuXVcBcjL._SX466_.jpg",
    featured: false,
    keyIngredient: "Gel Polish Formula",
    benefits: ["Long lasting", "Shiny finish", "Chip resistant"],
    fullDescription:
      "Set of 6 neutral gel polish colors for DIY gel manicures. Professional quality formula that lasts 2+ weeks with proper application.",
    howToUse: [
      "Apply base coat and cure",
      "Apply color in thin layers, cure each",
      "Apply top coat and cure",
      "Wipe with alcohol if needed",
    ],
    bestFor: ["DIY manicures", "Long-lasting nails", "Special occasions", "Neutral colors"],
    proscons: {
      pros: ["Beautiful colors", "Lasts 2+ weeks", "Affordable", "Neutral shades"],
      cons: ["Bottles are small", "Requires UV lamp", "Learning curve"],
    },
    amazonLink: "https://www.amazon.com/Polish-Light-include-Colors-Manicure/dp/B097BSKN9P",
  },
  {
    slug: "cutex-ultra-powerful-remover",
    name: "Cutex Ultra Powerful Nail Polish Remover",
    brand: "Cutex",
    rating: 4.7,
    reviews: 8000,
    price: "$4.99",
    image: "https://m.media-amazon.com/images/I/71V9fvCghJL._SX466_.jpg",
    featured: false,
    keyIngredient: "Acetone",
    benefits: ["Removes tough polish", "Fast acting", "Effective"],
    fullDescription:
      "Strong remover for glitter, gel, and dark polishes. Acetone formula cuts through the toughest polish quickly and efficiently.",
    howToUse: [
      "Soak cotton pad and wipe nail",
      "Hold for a few seconds for gel polish",
      "Wash hands after use",
      "Moisturize nails and cuticles",
    ],
    bestFor: ["Gel removal", "Glitter polish", "Dark colors", "Nail prep"],
    proscons: {
      pros: ["Very effective", "Cheap", "Works fast", "Widely available"],
      cons: ["Drying to skin", "Strong smell", "Acetone formula"],
    },
    amazonLink: "https://www.amazon.com/Cutex-Ultra-Powerful-Nail-Polish-Remover/dp/B06XBBS1WP",
  },
  {
    slug: "hard-as-hoof-nail-strengthening-cream",
    name: "Hard As Hoof Nail Strengthening Cream",
    brand: "Hard As Hoof",
    rating: 4.6,
    reviews: 55000,
    price: "$7.94",
    image: "https://m.media-amazon.com/images/I/51KnnAg1XlL._SL1042_.jpg",
    featured: false,
    keyIngredient: "Vitamins & Minerals",
    benefits: ["Strengthens nails", "Conditions cuticles", "Promotes growth"],
    fullDescription:
      "Nail treatment to prevent splits, chips, and cracks. Enriched with vitamins and minerals to strengthen weak nails and condition cuticles.",
    howToUse: [
      "Massage into nails and cuticles daily",
      "Use before bed for overnight treatment",
      "Apply after hand washing",
    ],
    bestFor: ["Weak nails", "Brittle nails", "Cuticle care", "Nail growth"],
    proscons: {
      pros: ["Works well", "Pleasant smell", "Affordable", "High reviews", "Cult favorite"],
      cons: ["Can be greasy", "Takes time to see results", "Strong coconut scent"],
    },
    amazonLink: "https://www.amazon.com/Strengthening-Coconut-Strengthener-Conditioning-Strengthens/dp/B005HGWGVS",
  },
  {
    slug: "nyk1-nail-glue",
    name: "NYK1 Nail Bond Super Strong Glue",
    brand: "NYK1",
    rating: 4.5,
    reviews: 22000,
    price: "$14.95",
    image: "https://m.media-amazon.com/images/I/71P3QkBRapL._SY500_.jpg",
    featured: false,
    keyIngredient: "Cyanoacrylate",
    benefits: ["Strong hold", "Easy application", "Long lasting"],
    fullDescription:
      "Professional grade brush-on nail glue for tips and nail art. Super strong bond that lasts for weeks with proper application.",
    howToUse: [
      "Brush onto nail and press tip for 10 seconds",
      "Apply thin layer for best results",
      "Remove excess immediately",
      "Store upright with cap tight",
    ],
    bestFor: ["Press-on nails", "Nail tips", "Nail art", "Nail repairs"],
    proscons: {
      pros: ["Brush applicator", "Very strong", "Professional quality", "Long lasting"],
      cons: ["Hard to remove", "Can damage natural nails", "Strong fumes"],
    },
    amazonLink: "https://www.amazon.com/NYK1-Nail-Glue-Super-Strong-Bond/dp/B01I70RA8E",
  },
  {
    slug: "truskin-vitamin-c-serum",
    name: "TruSkin Vitamin C Serum",
    brand: "TruSkin",
    rating: 4.6,
    reviews: 140000,
    price: "$21.95",
    image: "https://m.media-amazon.com/images/I/5122abFTZpL._SL1250_.jpg",
    featured: true,
    keyIngredient: "Vitamin C 20%",
    benefits: ["Brightens skin", "Fades dark spots", "Reduces wrinkles"],
    fullDescription:
      "Anti-aging serum with Vitamin C, E and Hyaluronic Acid. Best-selling formula that brightens, firms, and hydrates for youthful-looking skin.",
    activeIngredients: [
      { name: "Vitamin C", concentration: "20%", benefit: "Brightens and protects" },
      { name: "Vitamin E", concentration: "N/A", benefit: "Antioxidant support" },
      { name: "Hyaluronic Acid", concentration: "N/A", benefit: "Hydrates and plumps" },
    ],
    howToUse: [
      "Apply 3-5 drops to clean face morning and night",
      "Gently massage until absorbed",
      "Follow with moisturizer",
      "Always use SPF during day",
    ],
    bestFor: ["Dark spots", "Dull skin", "Fine lines", "All skin types"],
    proscons: {
      pros: ["Cult favorite", "Effective brightening", "Great value", "Clean ingredients", "140K+ reviews"],
      cons: ["Can oxidize over time", "Slight orange tint", "May sting sensitive skin"],
    },
    amazonLink: "https://www.amazon.com/TruSkin-Naturals-Vitamin-Topical-Hyaluronic/dp/B01EKUBU5Y",
  },
]
